version: "3"
services:
  app:
   build: ./
   image: dalongrong/openresty-lua-resty-shell
   ports:
   - "8080:80"
   volumes:
   - "./app/:/opt/app/"
   - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
